---
title: "Offentlige dokumenter"
---


## Servitutter og deklarationer

::: columns
::: {.column width="55%"}
Her finder du tinglyste servitutter og deklarationer for vores område. En servitut er en bestemmelse knyttet til en fast ejendom, som begrænser ejerens ret til at råde over den. En servitut og en deklaration er det samme.
:::

::: {.column width="5%"}
:::

::: {.column width="40%"}
-   [Servitut - Udstykning af Grønnessegård, 1965](dok_offentlig/Servitutter - Udstykning af Groennessegaard.pdf)
-   [Deklaration - Ret til sti og ophold og badning på strand, 1965](dok_offentlig/Deklaration-Ret til ophold og badning paa stranden.pdf)
-   [Deklaration om fredning, 1965](dok_offentlig/%20Deklaration%20om%20fredning.pdf)
:::
:::

## Lokalplan

::: columns
::: {.column width="55%"}
Her finder du "Lokalplan nr. 16 for et område under Grønnessegård hovedgård" fra 1978.
:::

::: {.column width="5%"}
:::

::: {.column width="40%"}
-   [Lokalplan, 1978](dok_offentlig/Lokalplan%2016.pdf)
:::
:::

## Halsnæs Kommune

::: columns
::: {.column width="55%"}
Her finder du info fra Halsnæs Kommune om beskæring af træer og buske langs veje.
:::

::: {.column width="5%"}
:::

::: {.column width="40%"}
-   [Folder fra 2008](dok_offentlig/beskaering-beplantning-halsneas-2008.pdf)
-   [Halsnæs Kommune hjemmeside - se under "Beskæring og beplantning"](https://halsnaes.dk/borger/trafik-og-veje/veje-fortov-og-stier){target="_blank"}
:::
:::